//! DS9 region files: parsing and conversion to image-pixel space.
//!
//! Design constraints (same as `fits`/`wcs`):
//! - No Tauri types; pure and unit-testable.
//! - Correctness gated on fixtures generated by the astropy `regions`
//!   package (scripts/gen_region_fixtures.py → fixtures/regions/ +
//!   regions_expected.json; tests in tests/region_fixtures.rs). The
//!   sky→pixel math below reproduces regions 0.12's algorithms exactly.
//!
//! Scope (M3):
//! - Shapes: circle, annulus, ellipse, box, polygon, point. Others (line,
//!   text, panda, …) are skipped with a warning.
//! - Frames: image/physical (pixel coords) and fk5/icrs/j2000 (sky).
//!   fk5 is treated as an alias of icrs — the ~23 mas frame rotation is
//!   ignored (well under a pixel for typical imaging; exact frame
//!   conversion is a backlog item). Galactic etc. → regions skipped with
//!   a warning.

pub mod parse;
pub mod write;

use crate::wcs::Wcs;
use serde::{Deserialize, Serialize};

const ARCSEC_PER_RAD: f64 = 3600.0 * 180.0 / std::f64::consts::PI;

/// Coordinate frame a region's numbers are expressed in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Frame {
    /// DS9 image/physical coords: 1-based pixels, sizes in pixels,
    /// angles in degrees CCW from +x.
    Image,
    /// Sky coords: positions in degrees (RA, Dec), sizes in arcsec,
    /// angles in degrees (DS9 convention, as consumed by astropy-regions).
    Sky,
}

/// Shape parameters, in the units of the region's `Frame` (see above).
#[derive(Debug, Clone, PartialEq)]
pub enum Shape {
    Circle { x: f64, y: f64, r: f64 },
    /// Circular annulus (a multi-radius DS9 annulus is expanded to one
    /// region per consecutive radius pair at parse time, like astropy).
    Annulus { x: f64, y: f64, rin: f64, rout: f64 },
    /// rx/ry are semi-axes (DS9 writes semi-axes for ellipses).
    Ellipse { x: f64, y: f64, rx: f64, ry: f64, angle: f64 },
    /// w/h are full side lengths (DS9 box convention).
    Box { x: f64, y: f64, w: f64, h: f64, angle: f64 },
    Polygon { pts: Vec<(f64, f64)> },
    Point { x: f64, y: f64 },
}

/// Display properties (global line merged with per-shape overrides).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Props {
    pub color: Option<String>,
    pub width: Option<f64>,
    pub dash: Option<bool>,
    pub text: Option<String>,
    /// Point marker style ("circle", "cross", "x", …).
    pub point: Option<String>,
}

impl Props {
    /// Local values win; missing ones fall back to the global defaults.
    pub(crate) fn merged_over(&self, global: &Props) -> Props {
        Props {
            color: self.color.clone().or_else(|| global.color.clone()),
            width: self.width.or(global.width),
            dash: self.dash.or(global.dash),
            text: self.text.clone().or_else(|| global.text.clone()),
            point: self.point.clone().or_else(|| global.point.clone()),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Region {
    pub frame: Frame,
    pub shape: Shape,
    /// false for excluded ("-"-prefixed) regions.
    pub include: bool,
    pub props: Props,
}

/// Result of parsing one .reg file. Warnings are user-facing notes about
/// skipped/unsupported content — parsing never hard-fails on one bad line.
#[derive(Debug, Default)]
pub struct RegionFile {
    pub regions: Vec<Region>,
    pub warnings: Vec<String>,
}

/// A region resolved to image-pixel space (FITS 0-based pixel centers,
/// matching the viewer and astropy-regions PixelRegion conventions;
/// angles in degrees CCW from +x).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "shape", rename_all = "lowercase")]
pub enum PixelShape {
    Circle { x: f64, y: f64, r: f64 },
    Annulus { x: f64, y: f64, rin: f64, rout: f64 },
    Ellipse { x: f64, y: f64, rx: f64, ry: f64, angle: f64 },
    Box { x: f64, y: f64, w: f64, h: f64, angle: f64 },
    Polygon { xs: Vec<f64>, ys: Vec<f64> },
    Point { x: f64, y: f64 },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PixelRegion {
    #[serde(flatten)]
    pub shape: PixelShape,
    pub include: bool,
    pub color: Option<String>,
    pub width: Option<f64>,
    pub dash: bool,
    pub text: Option<String>,
    pub point: Option<String>,
}

impl Region {
    /// Resolve to pixel space. Sky-frame regions need a WCS; errors are
    /// user-facing strings (caller typically downgrades them to warnings).
    pub fn to_pixel(&self, wcs: Option<&Wcs>) -> Result<PixelRegion, String> {
        let shape = match self.frame {
            Frame::Image => image_to_pixel(&self.shape),
            Frame::Sky => {
                let w = wcs.ok_or("sky-frame region, but the HDU has no supported WCS")?;
                sky_to_pixel(&self.shape, w)?
            }
        };
        Ok(PixelRegion {
            shape,
            include: self.include,
            color: self.props.color.clone(),
            width: self.props.width,
            dash: self.props.dash.unwrap_or(false),
            text: self.props.text.clone(),
            point: self.props.point.clone(),
        })
    }
}

impl PixelRegion {
    fn props(&self) -> Props {
        Props {
            color: self.color.clone(),
            width: self.width,
            dash: if self.dash { Some(true) } else { None },
            text: self.text.clone(),
            point: self.point.clone(),
        }
    }

    /// Serialize back to a DS9 image-frame region (1-based pixel centers).
    /// Exact inverse of `image_to_pixel`.
    pub fn to_image_region(&self) -> Region {
        let shape = match self.shape {
            PixelShape::Circle { x, y, r } => Shape::Circle { x: x + 1.0, y: y + 1.0, r },
            PixelShape::Annulus { x, y, rin, rout } => {
                Shape::Annulus { x: x + 1.0, y: y + 1.0, rin, rout }
            }
            PixelShape::Ellipse { x, y, rx, ry, angle } => {
                Shape::Ellipse { x: x + 1.0, y: y + 1.0, rx, ry, angle }
            }
            PixelShape::Box { x, y, w, h, angle } => {
                Shape::Box { x: x + 1.0, y: y + 1.0, w, h, angle }
            }
            PixelShape::Polygon { ref xs, ref ys } => Shape::Polygon {
                pts: xs.iter().zip(ys).map(|(x, y)| (x + 1.0, y + 1.0)).collect(),
            },
            PixelShape::Point { x, y } => Shape::Point { x: x + 1.0, y: y + 1.0 },
        };
        Region { frame: Frame::Image, shape, include: self.include, props: self.props() }
    }

    /// Serialize back to a sky (icrs) region through a WCS — the inverse of
    /// `sky_to_pixel`: positions via `pix_to_world`, circle/annulus radii via
    /// the local pixel scale, ellipse/box via the pixel→sky SVD. Round-trips
    /// with `to_pixel` (asserted in tests/region_fixtures.rs).
    pub fn to_sky_region(&self, w: &Wcs) -> Result<Region, String> {
        let world = |x: f64, y: f64| w.pix_to_world(x, y);
        let shape = match self.shape {
            PixelShape::Circle { x, y, r } => {
                let (ra, dec) = world(x, y);
                Shape::Circle { x: ra, y: dec, r: r * local_scale_arcsec(w, x, y) }
            }
            PixelShape::Annulus { x, y, rin, rout } => {
                let (ra, dec) = world(x, y);
                let s = local_scale_arcsec(w, x, y);
                Shape::Annulus { x: ra, y: dec, rin: rin * s, rout: rout * s }
            }
            PixelShape::Ellipse { x, y, rx, ry, angle } => {
                let (ra, dec, sw, sh, pa) = sky_shape_via_svd(w, x, y, 2.0 * rx, 2.0 * ry, angle)?;
                Shape::Ellipse { x: ra, y: dec, rx: sw / 2.0, ry: sh / 2.0, angle: pa }
            }
            PixelShape::Box { x, y, w: bw, h: bh, angle } => {
                let (ra, dec, sw, sh, pa) = sky_shape_via_svd(w, x, y, bw, bh, angle)?;
                Shape::Box { x: ra, y: dec, w: sw, h: sh, angle: pa }
            }
            PixelShape::Polygon { ref xs, ref ys } => Shape::Polygon {
                pts: xs.iter().zip(ys).map(|(&x, &y)| world(x, y)).collect(),
            },
            PixelShape::Point { x, y } => {
                let (ra, dec) = world(x, y);
                Shape::Point { x: ra, y: dec }
            }
        };
        Ok(Region { frame: Frame::Sky, shape, include: self.include, props: self.props() })
    }
}

/// DS9 image coords are 1-based pixel centers; the viewer (and astropy
/// regions) use 0-based. Sizes and angles carry over unchanged.
fn image_to_pixel(shape: &Shape) -> PixelShape {
    match *shape {
        Shape::Circle { x, y, r } => PixelShape::Circle { x: x - 1.0, y: y - 1.0, r },
        Shape::Annulus { x, y, rin, rout } => {
            PixelShape::Annulus { x: x - 1.0, y: y - 1.0, rin, rout }
        }
        Shape::Ellipse { x, y, rx, ry, angle } => PixelShape::Ellipse {
            x: x - 1.0,
            y: y - 1.0,
            rx,
            ry,
            angle: angle.rem_euclid(360.0),
        },
        Shape::Box { x, y, w, h, angle } => PixelShape::Box {
            x: x - 1.0,
            y: y - 1.0,
            w,
            h,
            angle: angle.rem_euclid(360.0),
        },
        Shape::Polygon { ref pts } => PixelShape::Polygon {
            xs: pts.iter().map(|p| p.0 - 1.0).collect(),
            ys: pts.iter().map(|p| p.1 - 1.0).collect(),
        },
        Shape::Point { x, y } => PixelShape::Point { x: x - 1.0, y: y - 1.0 },
    }
}

fn sky_to_pixel(shape: &Shape, w: &Wcs) -> Result<PixelShape, String> {
    let project = |ra: f64, dec: f64| -> Result<(f64, f64), String> {
        w.world_to_pix(ra, dec)
            .ok_or_else(|| "region center is on the far side of the sky".to_string())
    };
    Ok(match *shape {
        Shape::Circle { x: ra, y: dec, r } => {
            let (x, y) = project(ra, dec)?;
            PixelShape::Circle { x, y, r: r / local_scale_arcsec(w, x, y) }
        }
        Shape::Annulus { x: ra, y: dec, rin, rout } => {
            let (x, y) = project(ra, dec)?;
            let s = local_scale_arcsec(w, x, y);
            PixelShape::Annulus { x, y, rin: rin / s, rout: rout / s }
        }
        Shape::Ellipse { x: ra, y: dec, rx, ry, angle } => {
            let (x, y, pw, ph, pa) = shape_via_svd(w, ra, dec, 2.0 * rx, 2.0 * ry, angle)?;
            PixelShape::Ellipse { x, y, rx: pw / 2.0, ry: ph / 2.0, angle: pa }
        }
        Shape::Box { x: ra, y: dec, w: bw, h: bh, angle } => {
            let (x, y, pw, ph, pa) = shape_via_svd(w, ra, dec, bw, bh, angle)?;
            PixelShape::Box { x, y, w: pw, h: ph, angle: pa }
        }
        Shape::Polygon { ref pts } => {
            let mut xs = Vec::with_capacity(pts.len());
            let mut ys = Vec::with_capacity(pts.len());
            for &(ra, dec) in pts {
                let (x, y) = project(ra, dec)?;
                xs.push(x);
                ys.push(y);
            }
            PixelShape::Polygon { xs, ys }
        }
        Shape::Point { x: ra, y: dec } => {
            let (x, y) = project(ra, dec)?;
            PixelShape::Point { x, y }
        }
    })
}

// --- spherical helpers (radians; same formulas as astropy) ---------------

/// Great-circle separation (Vincenty formula, like astropy's separation).
fn separation(lon1: f64, lat1: f64, lon2: f64, lat2: f64) -> f64 {
    let (sdlon, cdlon) = (lon2 - lon1).sin_cos();
    let (slat1, clat1) = lat1.sin_cos();
    let (slat2, clat2) = lat2.sin_cos();
    let num1 = clat2 * sdlon;
    let num2 = clat1 * slat2 - slat1 * clat2 * cdlon;
    num1.hypot(num2).atan2(slat1 * slat2 + clat1 * clat2 * cdlon)
}

/// Position angle of point 2 as seen from point 1, measured from North
/// toward East (astropy `position_angle` convention).
fn position_angle(lon1: f64, lat1: f64, lon2: f64, lat2: f64) -> f64 {
    let (sdlon, cdlon) = (lon2 - lon1).sin_cos();
    let (slat1, clat1) = lat1.sin_cos();
    let (slat2, clat2) = lat2.sin_cos();
    (sdlon * clat2).atan2(clat1 * slat2 - slat1 * clat2 * cdlon)
}

/// Sky position of pixel (x, y) in radians.
fn pix_to_world_rad(w: &Wcs, x: f64, y: f64) -> (f64, f64) {
    let (ra, dec) = w.pix_to_world(x, y);
    (ra.to_radians(), dec.to_radians())
}

/// Local isotropic pixel scale (arcsec/pixel) at pixel (x, y): geometric
/// mean of the two 1-pixel step separations. This is astropy-regions'
/// `wcs_pixel_scale_angle` scale, used for sky circles.
fn local_scale_arcsec(w: &Wcs, x: f64, y: f64) -> f64 {
    let s0 = pix_to_world_rad(w, x, y);
    let sx = pix_to_world_rad(w, x + 1.0, y);
    let sy = pix_to_world_rad(w, x, y + 1.0);
    let cdelt_x = separation(s0.0, s0.1, sx.0, sx.1) * ARCSEC_PER_RAD;
    let cdelt_y = separation(s0.0, s0.1, sy.0, sy.1) * ARCSEC_PER_RAD;
    (cdelt_x * cdelt_y).sqrt()
}

/// Local Jacobian J = d(pixel)/d(tangent-plane arcsec) at pixel (x, y),
/// from 1-pixel finite differences (astropy-regions'
/// `compute_local_wcs_jacobian`). Tangent axes: xi = East, eta = North.
fn jacobian(w: &Wcs, x: f64, y: f64) -> Result<[[f64; 2]; 2], String> {
    let s0 = pix_to_world_rad(w, x, y);
    let mut fwd = [[0.0f64; 2]; 2];
    for (col, s) in [
        pix_to_world_rad(w, x + 1.0, y),
        pix_to_world_rad(w, x, y + 1.0),
    ]
    .iter()
    .enumerate()
    {
        let sep = separation(s0.0, s0.1, s.0, s.1) * ARCSEC_PER_RAD;
        let pa = position_angle(s0.0, s0.1, s.0, s.1);
        fwd[0][col] = sep * pa.sin(); // d(xi)
        fwd[1][col] = sep * pa.cos(); // d(eta)
    }
    let det = fwd[0][0] * fwd[1][1] - fwd[0][1] * fwd[1][0];
    if det == 0.0 || !det.is_finite() {
        return Err("degenerate WCS at region center".into());
    }
    Ok([
        [fwd[1][1] / det, -fwd[0][1] / det],
        [-fwd[1][0] / det, fwd[0][0] / det],
    ])
}

/// Sky ellipse/box → pixel center, full width/height and angle (deg CCW
/// from +x), reproducing astropy-regions' `sky_shape_to_pixel_svd`:
/// composite matrix M = J · M_sky, principal axes via SVD, width/height
/// assignment kept aligned with the input width axis.
fn shape_via_svd(
    w: &Wcs,
    ra: f64,
    dec: f64,
    width_asec: f64,
    height_asec: f64,
    angle_deg: f64,
) -> Result<(f64, f64, f64, f64, f64), String> {
    let (x, y) = w
        .world_to_pix(ra, dec)
        .ok_or_else(|| "region center is on the far side of the sky".to_string())?;
    let j = jacobian(w, x, y)?;

    // Sky angle → position angle from North (regions subtracts 90°).
    let (sin_pa, cos_pa) = (angle_deg - 90.0).to_radians().sin_cos();
    let (hw, hh) = (width_asec / 2.0, height_asec / 2.0);
    let m_sky = [[hw * sin_pa, hh * cos_pa], [hw * cos_pa, -hh * sin_pa]];
    let m = [
        [
            j[0][0] * m_sky[0][0] + j[0][1] * m_sky[1][0],
            j[0][0] * m_sky[0][1] + j[0][1] * m_sky[1][1],
        ],
        [
            j[1][0] * m_sky[0][0] + j[1][1] * m_sky[1][0],
            j[1][0] * m_sky[0][1] + j[1][1] * m_sky[1][1],
        ],
    ];

    // numpy.isclose defaults, as used for regions' input_circular flag.
    let circular = (width_asec - height_asec).abs() <= 1e-8 + 1e-5 * height_asec.abs();
    let (pw, ph, angle) = svd_ellipse(m, circular);
    Ok((x, y, pw, ph, angle))
}

fn invert2x2(m: [[f64; 2]; 2]) -> Result<[[f64; 2]; 2], String> {
    let det = m[0][0] * m[1][1] - m[0][1] * m[1][0];
    if det == 0.0 || !det.is_finite() {
        return Err("degenerate WCS at region center".into());
    }
    Ok([
        [m[1][1] / det, -m[0][1] / det],
        [-m[1][0] / det, m[0][0] / det],
    ])
}

fn matmul2(a: [[f64; 2]; 2], b: [[f64; 2]; 2]) -> [[f64; 2]; 2] {
    [
        [
            a[0][0] * b[0][0] + a[0][1] * b[1][0],
            a[0][0] * b[0][1] + a[0][1] * b[1][1],
        ],
        [
            a[1][0] * b[0][0] + a[1][1] * b[1][0],
            a[1][0] * b[0][1] + a[1][1] * b[1][1],
        ],
    ]
}

/// Pixel ellipse/box → sky center, full width/height (arcsec) and DS9 angle
/// (deg). Inverse of `shape_via_svd`: build the pixel semi-axis matrix from
/// (width, height, angle), map it into the tangent plane with J⁻¹, then take
/// principal axes via the same SVD. The angle relation is the inverse of the
/// forward's `angle - 90` position-angle convention (verified by the pixel↔
/// sky round-trip test).
fn sky_shape_via_svd(
    w: &Wcs,
    x: f64,
    y: f64,
    width_pix: f64,
    height_pix: f64,
    angle_deg: f64,
) -> Result<(f64, f64, f64, f64, f64), String> {
    let (ra, dec) = w.pix_to_world(x, y);
    let j = jacobian(w, x, y)?; // d(pixel)/d(tangent arcsec)
    let a = invert2x2(j)?; // d(tangent arcsec)/d(pixel)
    let (hw, hh) = (width_pix / 2.0, height_pix / 2.0);
    let (s, c) = angle_deg.to_radians().sin_cos();
    // Columns: mapped width and height semi-axis vectors in pixel space.
    let m_pix = [[hw * c, -hh * s], [hw * s, hh * c]];
    let m_sky = matmul2(a, m_pix);
    let circular = (width_pix - height_pix).abs() <= 1e-8 + 1e-5 * height_pix.abs();
    let (sw, sh, ang_t) = svd_ellipse(m_sky, circular);
    // Forward built the width axis in tangent coords as (sin_pa, cos_pa) with
    // pa = angle_sky - 90, so ang_t = atan2(cos_pa, sin_pa) = 90 - pa, giving
    // angle_sky = pa + 90 = 180 - ang_t.
    let sky_angle = (180.0 - ang_t).rem_euclid(360.0);
    Ok((ra, dec, sw, sh, sky_angle))
}

/// Principal axes of the composite 2×2 matrix (columns = mapped width and
/// height semi-axis vectors). Returns (full width, full height, angle°),
/// mirroring regions' `_svd_ellipse_from_composite`.
fn svd_ellipse(m: [[f64; 2]; 2], input_circular: bool) -> (f64, f64, f64) {
    // Singular values/left vectors via the eigenstructure of M·Mᵀ.
    let p = m[0][0] * m[0][0] + m[0][1] * m[0][1];
    let r = m[1][0] * m[1][0] + m[1][1] * m[1][1];
    let q = m[0][0] * m[1][0] + m[0][1] * m[1][1];
    let mean = (p + r) / 2.0;
    let diff = ((p - r) / 2.0).hypot(q);
    let s1 = (mean + diff).max(0.0).sqrt();
    let s2 = (mean - diff).max(0.0).sqrt();
    let phi = 0.5 * (2.0 * q).atan2(p - r);
    let u1 = [phi.cos(), phi.sin()]; // direction of the major axis
    let u2 = [-phi.sin(), phi.cos()];

    // Column 0 of M is the mapped width semi-axis: keep the width/height
    // assignment aligned with it.
    let wcol = [m[0][0], m[1][0]];
    let dot = |a: [f64; 2], b: [f64; 2]| a[0] * b[0] + a[1] * b[1];
    let (out_w, out_h, mut acol) = if dot(u1, wcol).abs() >= dot(u2, wcol).abs() {
        (2.0 * s1, 2.0 * s2, u1)
    } else {
        (2.0 * s2, 2.0 * s1, u2)
    };
    if dot(acol, wcol) < 0.0 {
        acol = [-acol[0], -acol[1]];
    }
    // Circular input: SVD direction is arbitrary; use the mapped width
    // axis so the input rotation angle carries through.
    if input_circular {
        let n = wcol[0].hypot(wcol[1]);
        if n > 0.0 {
            acol = [wcol[0] / n, wcol[1] / n];
        }
    }
    let mut angle = acol[1].atan2(acol[0]).to_degrees().rem_euclid(360.0);
    if angle >= 360.0 {
        // rem_euclid of a tiny negative rounds to exactly 360.0.
        angle = 0.0;
    }
    (out_w, out_h, angle)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn svd_identity_jacobian_passthrough() {
        // M columns = semi-axes of an axis-aligned 4×2 ellipse (PA 90° from
        // North = along +x): width axis (2, 0), height axis (0, 1).
        let (w, h, angle) = svd_ellipse([[2.0, 0.0], [0.0, 1.0]], false);
        assert!((w - 4.0).abs() < 1e-12 && (h - 2.0).abs() < 1e-12);
        assert!(angle.abs() < 1e-12, "angle {angle}");
    }

    #[test]
    fn svd_height_major_keeps_width_assignment() {
        // Height axis longer than width axis: width stays the smaller one.
        let (w, h, angle) = svd_ellipse([[1.0, 0.0], [0.0, 3.0]], false);
        assert!((w - 2.0).abs() < 1e-12 && (h - 6.0).abs() < 1e-12);
        assert!(angle.abs() < 1e-12, "angle {angle}");
    }

    #[test]
    fn svd_sign_flip_aligns_with_width_column() {
        // Width column pointing in -x: angle flips to 180°.
        let (w, h, angle) = svd_ellipse([[-2.0, 0.0], [0.0, 1.0]], false);
        assert!((w - 4.0).abs() < 1e-12 && (h - 2.0).abs() < 1e-12);
        assert!((angle - 180.0).abs() < 1e-12, "angle {angle}");
    }

    #[test]
    fn image_frame_shifts_to_zero_based() {
        let region = Region {
            frame: Frame::Image,
            shape: Shape::Circle { x: 32.0, y: 24.0, r: 10.5 },
            include: true,
            props: Props::default(),
        };
        let pix = region.to_pixel(None).unwrap();
        match pix.shape {
            PixelShape::Circle { x, y, r } => {
                assert_eq!((x, y, r), (31.0, 23.0, 10.5));
            }
            other => panic!("wrong shape {other:?}"),
        }
    }

    #[test]
    fn sky_region_without_wcs_errors() {
        let region = Region {
            frame: Frame::Sky,
            shape: Shape::Point { x: 150.0, y: 2.0 },
            include: true,
            props: Props::default(),
        };
        assert!(region.to_pixel(None).is_err());
    }
}
