#!/usr/bin/env python
"""Generate ground-truth FITS fixtures for DS10's Rust tests.

astropy is the reference implementation: this script writes small FITS files
plus an expected.json capturing what a correct parser must report. Rust tests
(src-tauri/tests/fixtures.rs) compare against it. Regenerate with:

    scripts/venv/bin/python scripts/gen_fixtures.py
"""

import json
from pathlib import Path

import numpy as np
from astropy.io import fits
from astropy.visualization import ZScaleInterval
from astropy.wcs import WCS

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"


def build_sample() -> fits.HDUList:
    # Primary: float32 image with a deterministic pattern, TAN WCS, and
    # awkward header cards (quoted quote, D-exponent, blank-ish values).
    ny, nx = 48, 64
    yy, xx = np.mgrid[0:ny, 0:nx]
    data = (np.sin(xx / 7.0) * 100.0 + yy * 3.0).astype(np.float32)
    data[10, 20] = np.float32(-999.25)
    # NaN block: blank mosaic coverage; the viewer and zscale must skip it.
    data[0:4, 40:44] = np.nan
    primary = fits.PrimaryHDU(data=data)
    h = primary.header
    h["OBJECT"] = ("O'NEILL FIELD", "target with escaped quote")
    h["CTYPE1"] = "RA---TAN"
    h["CTYPE2"] = "DEC--TAN"
    h["CRVAL1"] = (150.1163213, "[deg] RA at reference pixel")
    h["CRVAL2"] = (2.2058057, "[deg] Dec at reference pixel")
    h["CRPIX1"] = 32.0
    h["CRPIX2"] = 24.0
    h["CD1_1"] = -8.333333e-06
    h["CD1_2"] = 0.0
    h["CD2_1"] = 0.0
    h["CD2_2"] = 8.333333e-06
    h["EXPTIME"] = (1200.0, "[s] exposure time")
    h["OBSERVER"] = "DS10 FIXTURES"
    h.add_comment("synthetic fixture generated by gen_fixtures.py")
    h.add_history("created for ds10 parser tests")

    # Int16 extension with BSCALE/BZERO to test scaling.
    # do_not_scale keeps our explicit BSCALE/BZERO instead of astropy managing them.
    idata = (np.arange(ny * nx, dtype=np.int32).reshape(ny, nx) % 60000) - 30000
    sci = fits.ImageHDU(data=idata.astype(np.int16), name="SCI", do_not_scale_image_data=True)
    sci.header["BSCALE"] = 2.0
    sci.header["BZERO"] = 100.0

    # Binary table extension.
    n = 123
    cols = fits.ColDefs(
        [
            fits.Column(name="ID", format="J", array=np.arange(n, dtype=np.int32)),
            fits.Column(name="RA", format="D", array=np.linspace(149.9, 150.3, n)),
            fits.Column(name="DEC", format="D", array=np.linspace(2.0, 2.4, n)),
            fits.Column(name="FLUX", format="E", array=np.random.default_rng(42).normal(size=n).astype(np.float32)),
            fits.Column(name="NAME", format="16A", array=np.array([f"src_{i:04d}" for i in range(n)])),
        ]
    )
    table = fits.BinTableHDU.from_columns(cols, name="CATALOG")

    # Tiny image HDUs exercising the WCS variants the Rust module supports.
    # Data content is irrelevant; only the headers matter.
    tiny = np.zeros((24, 32), dtype=np.float32)

    # Rotated + slightly skewed CD matrix at high declination.
    rot = fits.ImageHDU(data=tiny, name="ROT")
    rot.header["CTYPE1"] = "RA---TAN"
    rot.header["CTYPE2"] = "DEC--TAN"
    rot.header["CRVAL1"] = 83.6331
    rot.header["CRVAL2"] = 61.2007
    rot.header["CRPIX1"] = 16.5
    rot.header["CRPIX2"] = 12.25
    rot.header["CD1_1"] = -2.11e-4 * np.cos(np.radians(33.0))
    rot.header["CD1_2"] = 2.05e-4 * np.sin(np.radians(33.0))
    rot.header["CD2_1"] = 2.11e-4 * np.sin(np.radians(33.0))
    rot.header["CD2_2"] = 2.05e-4 * np.cos(np.radians(33.0))

    # Legacy CDELT + CROTA2 form.
    rota = fits.ImageHDU(data=tiny, name="ROTA")
    rota.header["CTYPE1"] = "RA---TAN"
    rota.header["CTYPE2"] = "DEC--TAN"
    rota.header["CRVAL1"] = 210.802
    rota.header["CRVAL2"] = -12.454
    rota.header["CRPIX1"] = 10.0
    rota.header["CRPIX2"] = 14.0
    rota.header["CDELT1"] = -1.7e-4
    rota.header["CDELT2"] = 1.7e-4
    rota.header["CROTA2"] = -18.5

    # Latitude axis first (CTYPE1 = DEC--TAN): CRVAL1 is the Dec.
    swap = fits.ImageHDU(data=tiny, name="SWAP")
    swap.header["CTYPE1"] = "DEC--TAN"
    swap.header["CTYPE2"] = "RA---TAN"
    swap.header["CRVAL1"] = 2.2058057
    swap.header["CRVAL2"] = 150.1163213
    swap.header["CRPIX1"] = 8.0
    swap.header["CRPIX2"] = 20.0
    swap.header["CD1_1"] = 9.0e-5
    swap.header["CD1_2"] = -1.1e-5
    swap.header["CD2_1"] = 1.2e-5
    swap.header["CD2_2"] = 8.7e-5

    return fits.HDUList([primary, sci, table, rot, rota, swap])


def expectations(hdul: fits.HDUList, path: Path) -> dict:
    hdus = []
    for i, hdu in enumerate(hdul):
        kind = (
            "image"
            if isinstance(hdu, (fits.PrimaryHDU, fits.ImageHDU))
            else "bin_table"
            if isinstance(hdu, fits.BinTableHDU)
            else "unknown"
        )
        info = {
            "index": i,
            "kind": kind,
            "name": hdu.header.get("EXTNAME"),
            "bitpix": hdu.header["BITPIX"],
            # FITS axis order (NAXIS1 first) to match the Rust side.
            "shape": [hdu.header[f"NAXIS{j}"] for j in range(1, hdu.header["NAXIS"] + 1)],
            "header_cards": {
                key: hdu.header[key]
                for key in ("OBJECT", "CRVAL1", "EXPTIME", "BSCALE", "BZERO", "TFIELDS")
                if key in hdu.header
            },
        }
        hdus.append(info)

    # Pixel spot checks: FITS 0-based (x, y) with scaling applied,
    # computed from the in-memory arrays (astropy applies BSCALE/BZERO
    # on read when scaling is active; use explicit math for the SCI HDU).
    with fits.open(path, do_not_scale_image_data=True) as raw:
        primary = raw[0].data
        sci = raw[1].data
        sci_scale = raw[1].header.get("BSCALE", 1.0)
        sci_zero = raw[1].header.get("BZERO", 0.0)
        checks = []
        for (x, y) in [(0, 0), (20, 10), (63, 47), (31, 24)]:
            checks.append({"hdu": 0, "x": x, "y": y, "value": float(primary[y, x])})
        for (x, y) in [(0, 0), (5, 3), (63, 47)]:
            checks.append(
                {"hdu": 1, "x": x, "y": y, "value": float(sci[y, x]) * sci_scale + sci_zero}
            )

    # Display-scaling and tile ground truth. Tiles are block-SAMPLED
    # (every 2^level-th pixel), so expected level-L values come from
    # numpy striding, and zscale limits from astropy's ZScaleInterval.
    with fits.open(path, do_not_scale_image_data=True) as raw:
        images = {
            0: raw[0].data.astype(np.float64),
            1: raw[1].data.astype(np.float64) * raw[1].header.get("BSCALE", 1.0)
            + raw[1].header.get("BZERO", 0.0),
        }

    def num_or_null(v: float) -> float | None:
        return None if np.isnan(v) else float(v)

    scale_checks = []
    for hdu_index, img in images.items():
        zlo, zhi = ZScaleInterval().get_limits(img)
        scale_checks.append(
            {
                "hdu": hdu_index,
                "zscale": [float(zlo), float(zhi)],
                "minmax": [float(np.nanmin(img)), float(np.nanmax(img))],
            }
        )

    tile_checks = []
    for hdu_index, img in images.items():
        for level in (0, 1):
            sampled = img[:: 2**level, :: 2**level]
            h, w = sampled.shape  # whole image fits in one 256px tile
            samples = []
            for (i, j) in [(0, 0), (w - 1, h - 1), (w // 2, h // 3), (5, 7)]:
                samples.append({"i": i, "j": j, "value": num_or_null(sampled[j, i])})
            if hdu_index == 0 and level == 0:
                # Inside the NaN block (x 40..44, y 0..4).
                samples.append({"i": 41, "j": 2, "value": None})
            tile_checks.append(
                {
                    "hdu": hdu_index,
                    "level": level,
                    "tx": 0,
                    "ty": 0,
                    "w": w,
                    "h": h,
                    "samples": samples,
                }
            )

    # WCS ground truth: astropy's TAN transform at reference, corner, and
    # fractional pixels (origin=0), plus world→pixel at nearby sky points.
    wcs_checks = []
    with fits.open(path) as raw:
        for hdu_index in (0, 3, 4, 5):
            header = raw[hdu_index].header
            w = WCS(header)
            nx, ny = header["NAXIS1"], header["NAXIS2"]
            pix_pts = [
                (0.0, 0.0),
                (nx - 1.0, ny - 1.0),
                (nx / 3.0, ny / 4.0),
                (10.25, 7.75),
            ]
            # astropy returns/accepts world values in WCS axis order, which
            # for the SWAP HDU is (dec, ra).
            lon_i, lat_i = (1, 0) if header["CTYPE1"].startswith("DEC") else (0, 1)
            p2w = []
            for (x, y) in pix_pts:
                world = w.wcs_pix2world([[x, y]], 0)[0]
                p2w.append(
                    {"x": x, "y": y, "ra": float(world[lon_i]), "dec": float(world[lat_i])}
                )
            # Sky points a bit off the field center (still on-image scale).
            ra0 = header[f"CRVAL{lon_i + 1}"]
            dec0 = header[f"CRVAL{lat_i + 1}"]
            w2p = []
            for (dra, ddec) in [(0.0, 0.0), (0.004, -0.003), (-0.0025, 0.0015)]:
                ra, dec = ra0 + dra, dec0 + ddec
                world = [ra, dec] if lon_i == 0 else [dec, ra]
                x, y = w.wcs_world2pix([world], 0)[0]
                w2p.append({"ra": float(ra), "dec": float(dec), "x": float(x), "y": float(y)})
            wcs_checks.append({"hdu": hdu_index, "pix2world": p2w, "world2pix": w2p})

    # Histogram ground truth: np.histogram over finite pixels, min..max range.
    hist_checks = []
    for hdu_index, img in images.items():
        finite = img[np.isfinite(img)]
        lo, hi = float(finite.min()), float(finite.max())
        counts, _ = np.histogram(finite, bins=16, range=(lo, hi))
        hist_checks.append(
            {
                "hdu": hdu_index,
                "bins": 16,
                "lo": lo,
                "hi": hi,
                "counts": [int(c) for c in counts],
            }
        )

    return {
        "file": path.name,
        "hdus": hdus,
        "pixel_checks": checks,
        "scale_checks": scale_checks,
        "tile_checks": tile_checks,
        "wcs_checks": wcs_checks,
        "hist_checks": hist_checks,
    }


def main() -> None:
    FIXTURES.mkdir(exist_ok=True)
    path = FIXTURES / "sample.fits"
    hdul = build_sample()
    hdul.writeto(path, overwrite=True, checksum=False)
    expected = expectations(hdul, path)
    (FIXTURES / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")
    print(f"wrote {path} ({path.stat().st_size} bytes) and expected.json")


if __name__ == "__main__":
    main()
