#!/usr/bin/env python
"""Generate src/render/colormaps.gen.ts — 256-entry RGB LUTs for the viewer.

matplotlib is the reference for the scientific maps (viridis family); the
DS9 classics (heat, cool) are piecewise-linear ramps transcribed from DS9's
.sao colormap definitions. The generated file is committed; regenerate with:

    scripts/venv/bin/python scripts/gen_colormaps.py
"""

from pathlib import Path

import numpy as np
from matplotlib import colormaps

OUT = Path(__file__).resolve().parent.parent / "src" / "render" / "colormaps.gen.ts"
N = 256


def matplotlib_lut(name: str) -> np.ndarray:
    cmap = colormaps[name]
    rgba = cmap(np.linspace(0.0, 1.0, N))
    return np.round(rgba[:, :3] * 255).astype(np.uint8)


def piecewise_lut(channels: dict[str, list[tuple[float, float]]]) -> np.ndarray:
    x = np.linspace(0.0, 1.0, N)
    lut = np.zeros((N, 3), dtype=np.uint8)
    for c, name in enumerate("rgb"):
        pts = channels[name]
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        lut[:, c] = np.round(np.interp(x, xs, ys) * 255).astype(np.uint8)
    return lut


# DS9 classic maps (piecewise-linear control points from DS9's .sao files).
DS9_HEAT = {
    "r": [(0.0, 0.0), (0.34, 1.0), (1.0, 1.0)],
    "g": [(0.0, 0.0), (1.0, 1.0)],
    "b": [(0.0, 0.0), (0.65, 0.0), (0.98, 1.0), (1.0, 1.0)],
}
DS9_COOL = {
    "r": [(0.0, 0.0), (0.29, 0.0), (0.76, 0.1), (1.0, 1.0)],
    "g": [(0.0, 0.0), (0.22, 0.0), (0.96, 1.0), (1.0, 1.0)],
    "b": [(0.0, 0.0), (0.53, 1.0), (1.0, 1.0)],
}

MAPS: list[tuple[str, np.ndarray]] = [
    ("gray", piecewise_lut({"r": [(0, 0), (1, 1)], "g": [(0, 0), (1, 1)], "b": [(0, 0), (1, 1)]})),
    ("viridis", matplotlib_lut("viridis")),
    ("inferno", matplotlib_lut("inferno")),
    ("magma", matplotlib_lut("magma")),
    ("plasma", matplotlib_lut("plasma")),
    ("heat", piecewise_lut(DS9_HEAT)),
    ("cool", piecewise_lut(DS9_COOL)),
]


def main() -> None:
    lines = [
        "// GENERATED by scripts/gen_colormaps.py — do not edit by hand.",
        "// 256-entry RGB LUTs, row-major [r,g,b, r,g,b, ...].",
        "",
        "export interface ColormapDef {",
        "  readonly name: string;",
        "  readonly rgb: Uint8Array; // 256 * 3",
        "}",
        "",
        "export const COLORMAPS: readonly ColormapDef[] = [",
    ]
    for name, lut in MAPS:
        flat = ", ".join(str(int(v)) for v in lut.reshape(-1))
        lines.append(f'  {{ name: "{name}", rgb: new Uint8Array([{flat}]) }},')
    lines.append("];")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(MAPS)} colormaps)")


if __name__ == "__main__":
    main()
