#!/usr/bin/env python
"""Generate ground-truth FITS fixtures for DS10's Rust tests.

astropy is the reference implementation: this script writes small FITS files
plus an expected.json capturing what a correct parser must report. Rust tests
(src-tauri/tests/fixtures.rs) compare against it. Regenerate with:

    scripts/venv/bin/python scripts/gen_fixtures.py
"""

import json
from pathlib import Path

import numpy as np
from astropy.io import fits

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"


def build_sample() -> fits.HDUList:
    # Primary: float32 image with a deterministic pattern, TAN WCS, and
    # awkward header cards (quoted quote, D-exponent, blank-ish values).
    ny, nx = 48, 64
    yy, xx = np.mgrid[0:ny, 0:nx]
    data = (np.sin(xx / 7.0) * 100.0 + yy * 3.0).astype(np.float32)
    data[10, 20] = np.float32(-999.25)
    primary = fits.PrimaryHDU(data=data)
    h = primary.header
    h["OBJECT"] = ("O'NEILL FIELD", "target with escaped quote")
    h["CTYPE1"] = "RA---TAN"
    h["CTYPE2"] = "DEC--TAN"
    h["CRVAL1"] = (150.1163213, "[deg] RA at reference pixel")
    h["CRVAL2"] = (2.2058057, "[deg] Dec at reference pixel")
    h["CRPIX1"] = 32.0
    h["CRPIX2"] = 24.0
    h["CD1_1"] = -8.333333e-06
    h["CD1_2"] = 0.0
    h["CD2_1"] = 0.0
    h["CD2_2"] = 8.333333e-06
    h["EXPTIME"] = (1200.0, "[s] exposure time")
    h["OBSERVER"] = "DS10 FIXTURES"
    h.add_comment("synthetic fixture generated by gen_fixtures.py")
    h.add_history("created for ds10 parser tests")

    # Int16 extension with BSCALE/BZERO to test scaling.
    # do_not_scale keeps our explicit BSCALE/BZERO instead of astropy managing them.
    idata = (np.arange(ny * nx, dtype=np.int32).reshape(ny, nx) % 60000) - 30000
    sci = fits.ImageHDU(data=idata.astype(np.int16), name="SCI", do_not_scale_image_data=True)
    sci.header["BSCALE"] = 2.0
    sci.header["BZERO"] = 100.0

    # Binary table extension.
    n = 123
    cols = fits.ColDefs(
        [
            fits.Column(name="ID", format="J", array=np.arange(n, dtype=np.int32)),
            fits.Column(name="RA", format="D", array=np.linspace(149.9, 150.3, n)),
            fits.Column(name="DEC", format="D", array=np.linspace(2.0, 2.4, n)),
            fits.Column(name="FLUX", format="E", array=np.random.default_rng(42).normal(size=n).astype(np.float32)),
            fits.Column(name="NAME", format="16A", array=np.array([f"src_{i:04d}" for i in range(n)])),
        ]
    )
    table = fits.BinTableHDU.from_columns(cols, name="CATALOG")

    return fits.HDUList([primary, sci, table])


def expectations(hdul: fits.HDUList, path: Path) -> dict:
    hdus = []
    for i, hdu in enumerate(hdul):
        kind = (
            "image"
            if isinstance(hdu, (fits.PrimaryHDU, fits.ImageHDU))
            else "bin_table"
            if isinstance(hdu, fits.BinTableHDU)
            else "unknown"
        )
        info = {
            "index": i,
            "kind": kind,
            "name": hdu.header.get("EXTNAME"),
            "bitpix": hdu.header["BITPIX"],
            # FITS axis order (NAXIS1 first) to match the Rust side.
            "shape": [hdu.header[f"NAXIS{j}"] for j in range(1, hdu.header["NAXIS"] + 1)],
            "header_cards": {
                key: hdu.header[key]
                for key in ("OBJECT", "CRVAL1", "EXPTIME", "BSCALE", "BZERO", "TFIELDS")
                if key in hdu.header
            },
        }
        hdus.append(info)

    # Pixel spot checks: FITS 0-based (x, y) with scaling applied,
    # computed from the in-memory arrays (astropy applies BSCALE/BZERO
    # on read when scaling is active; use explicit math for the SCI HDU).
    with fits.open(path, do_not_scale_image_data=True) as raw:
        primary = raw[0].data
        sci = raw[1].data
        sci_scale = raw[1].header.get("BSCALE", 1.0)
        sci_zero = raw[1].header.get("BZERO", 0.0)
        checks = []
        for (x, y) in [(0, 0), (20, 10), (63, 47), (31, 24)]:
            checks.append({"hdu": 0, "x": x, "y": y, "value": float(primary[y, x])})
        for (x, y) in [(0, 0), (5, 3), (63, 47)]:
            checks.append(
                {"hdu": 1, "x": x, "y": y, "value": float(sci[y, x]) * sci_scale + sci_zero}
            )

    return {"file": path.name, "hdus": hdus, "pixel_checks": checks}


def main() -> None:
    FIXTURES.mkdir(exist_ok=True)
    path = FIXTURES / "sample.fits"
    hdul = build_sample()
    hdul.writeto(path, overwrite=True, checksum=False)
    expected = expectations(hdul, path)
    (FIXTURES / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")
    print(f"wrote {path} ({path.stat().st_size} bytes) and expected.json")


if __name__ == "__main__":
    main()
